services:
  web:
    image: docker-icp
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: ["sh","-c", "npm i && npm start"]

  dfx:
    image: ghcr.io/dfinity/icp-dev-env:10
    depends_on:
      - web
    ports:
      - "4943:4943"
    volumes:
      - .:/app
    working_dir: /app
    command: ["sh","-c","dfx deploy"]
    healthcheck:
      test: ["CMD", "dfx", "status"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
    entrypoint: ["sh", "-c", "dfx start --host 0.0.0.0:4943 && npm i"]