# Continuous Deployment job to deploy the portal to the Internet Computer as an asset canister

name: CD

on:
  push:
    branches: [master]

jobs:
  deploy-ic:
    name: "Deploy to IC"
    runs-on: ubuntu-latest
    concurrency:
      group: "website update"
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - run: git submodule update --init
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install DFX
        uses: dfinity/setup-dfx@main
        with:
          dfx-version: "0.22.0"

      - name: Dump Identity
        run: |
            mkdir -p ~/.config/dfx/identity/main
            echo $DFX_IDENTITY | base64 -d > ~/.config/dfx/identity/main/identity.pem
        env:
          DFX_IDENTITY: ${{ secrets.DFX_IDENTITY }}


      - name: Install Dependencies
        run: npm install

      - name: Deploy to Mainnet
        run: dfx deploy --network=ic --no-wallet portal
